language: php

dist: bionic

php:
  - 8.0

jobs:
  include:
    - php: 8.0
      env: DB=mysql:5.7
    - php: 8.0
      env: DB=mysql:8.0

before_install:
  - composer self-update 1.10.16
  - phpenv config-rm xdebug.ini
  - mv .env.travis .env.testing
  - composer install -n --prefer-dist --no-scripts

script:
  - ./vendor/bin/phpunit
